void-linux/void-infrastructure

ansible/automation.yml
ansible/host_vars/vm2.a-lej-de.m.voidlinux.org.yml
ansible/inventory
ansible/roles/terrastate/files/root.conf
ansible/roles/terrastate/files/run
ansible/roles/terrastate/files/terrastate.rules
ansible/roles/terrastate/handlers/main.yml
ansible/roles/terrastate/meta/main.yml
ansible/roles/terrastate/tasks/main.yml
docs/src/terraform/index.md
terraform/backend.tf
terraform/google-dns.tf

This is all live and configured, primary review request is for documentation.

Support remote terraform state

---

docs/src/SUMMARY.md
docs/src/org/forum-moderation.md
docs/src/org/index.md
docs/src/org/offboarding.md
docs/src/org/onboarding.md

The technical bits are reasonably well documented, this change adds documentation for the human driven actions.
Specific reviews requested from other owners, general feedback requested from @void-linux/pkg-committers, all others feel free to bikeshed in the comments below.

Add DRBC Section

---

terraform/github_members.tf

This commit generates the following diff which will be applied after review and approval:
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
- destroy
Terraform will perform the following actions:
- github_team_membership.pkg-committers_maxice8
Plan: 0 to add, 0 to change, 1 to destroy.
```
Other access must be removed manually.
---
This PR automagically prepared by maldridge-bot.

terraform: offboard maxice8 per request

---

terraform/github_members.tf

After discussion and agreement from various areas of the project, I am pleased to present this PR to grant @Piraty a commit bit for -packages.
```
An execution plan has been generated and is shown below.                                                                                                                
Resource actions are indicated with the following symbols:                                                                                                              
+ create                                                                                                                                                              
Terraform will perform the following actions:                                       
+ resource "github_team_membership" "pkg-committers_piraty" { …
```

terraform: Add Piraty to pkg-committers

---

ansible/group_vars/build.yml

ansible: update DE-2 admin

---

terraform/github_members.tf

terraform: Add @sgn as pkg committer

---

terraform/github_members.tf

This is in reference to #67 
I am aware that a time for comments could be necessary according to the rules: https://infradocs.voidlinux.org/org/offboarding.html
However I'd like to not have this PR merged until Sunday to avoid heat-of-the-moment decisions.

terraform: Remove @xtraeme from xbps

---

terraform/github.tf
terraform/github_members.tf

Use the `for_each` meta-argument rather than many separate resources. While this will have a heck of a delta `terraform plan`-wise initially, after doing the necessary `terraform state mv` commands there should be no delta.

terraform: Use for_each on github resources

---

terraform/github_members.tf

Waiting on @ahesford to confirm acceptance of the offer.

terraform: Add @ahesford to pkg-committers

---

terraform/github/github_members.tf

@ericonr please reply here if you wish to accept this invite.

terraform/github: Invite @ericonr as a pkg-committer

---

ansible/build.yml
ansible/group_vars/build.yml
ansible/roles/btimefiles/files/run
ansible/roles/btimefiles/handlers/main.yml
ansible/roles/btimefiles/tasks/main.yml
ansible/roles/buildslave/templates/xbps-src.conf.j2
services/nomad/build/buildsync-aarch64.nomad
services/nomad/build/buildsync-musl.nomad
services/nomad/monitoring/grafana.nomad
services/nomad/monitoring/prometheus.nomad
services/nomad/monitoring/prometheus.yml
services/nomad/monitoring/repo_exporter.nomad
terraform/github/github.tf

Resolves #48, among other things.  Ultimate state is viewable on the following grafana dashboard: https://grafana.s.voidlinux.org/d/5w8Ft0UGk/internal-repository-status

various: Monitor internal mirror sync and stage status

---

terraform/github/github_members.tf

Welcome to the team @classabbyamp.  Please signify your acceptance of
this offer to join via a reply on this PR.
@duncaen for PR review.

terraform/github: Add @classabbyamp to pkg-committers

---

docs/src/services/netauth.md

also add section about forcing the entity ID

infradocs: update netauth section

---

services/pkg/nginx/Dockerfile
services/pkg/nginx/nginx.conf
services/pkg/nginx/root.conf

This paves the way for us to start templating things into sites.d/ to replace traefik.   I believe we should move to replace traefik soon in light of traefik/traefik#9108.

services/pkg/nginx: Support multiple sites.

---

services/nomad/build/xbps-sign-repos

for void-linux/void-packages#39868

services/nomad/build/xbps-sign-repos: update for bootstrap subrepo

---

.github/workflows/build-all.yml
.github/workflows/pkg-lsyncd.yml
services/pkg/docker-bake.hcl
services/pkg/lsyncd/Dockerfile

services/pkg/lsyncd: new service

---

ansible/inventory
ansible/man.yml

the role this ran has been removed and man-site is now in nomad

ansible/man.yml: remove

---

terraform/github/github_members.tf

@oreo639 Welcome Aboard.  Please signify your acceptance in this PR's thread.
@void-linux/void-ops for config delta:
```
Terraform will perform the following actions:
+ resource "github_team_membership" "team_membership" {
+ etag     = (known after apply)
+ id       = (known after apply)
+ role     = "member"
+ team_id  = "2795568"
+ username = "oreo639"
}
Plan: 1 to add, 0 to change, 0 to destroy.
```

terraform/github: Invite oreo639 to pkg-committers

---

docs/src/upkeep/images.md

draft while some details are ironed out

docs/src/upkeep/images: document github CI process, switch to minisign

---

terraform/github/github_members.tf

@tranzystorekk, please signify your acceptance of this offer to join the team with a reply to this thread.
@duncaen for infra approval.

terraform/github: Extend commit bit to @tranzystorekk

---

docs/src/postmortem/2024-07-27.md
services/nomad/apps/xmandump.nomad

**this change has been deployed successfully**

services/nomad/apps/xmandump: redeploy with newly built container

---

services/nomad/apps/devspace.nomad

env is now provided by nomad not docker

services/nomad/apps/devspace: update containers

---

services/nomad/apps/xmandump.nomad

services/nomad/apps/xmandump: update image

---

services/nomad/apps/man-cgi.nomad

updated infra-nginx, which backs this image

services/nomad/apps/man-cgi: update image
