ansible/group_vars/netlogon.yml, ansible/host_vars/vm2.a-lej-de.m.voidlinux.org.yml, ansible/inventory, ansible/netauth.yml, ansible/roles/netauth-config/files/netauth.rules, ansible/roles/netauth-config/files/netauth.toml, ansible/roles/netauth-config/tasks/main.yml, ansible/roles/netauthd/files/netauthd.rules, ansible/roles/netauthd/handlers/main.yml, ansible/roles/netauthd/meta/main.yml, ansible/roles/netauthd/tasks/main.yml, ansible/roles/netauthd/templates/run.j2, ansible/roles/netlogon/defaults/main.yml, ansible/roles/netlogon/files/base.policy, ansible/roles/netlogon/files/dante.sudoers, ansible/roles/netlogon/files/nsscache.run, ansible/roles/netlogon/files/nsswitch.conf, ansible/roles/netlogon/files/sudoers, ansible/roles/netlogon/files/system-auth, ansible/roles/netlogon/meta/main.yml, ansible/roles/netlogon/tasks/main.yml, ansible/roles/netlogon/templates/authorized_keys.j2
This PR adds the infrastructure to migrate all system accounts for Void infrastructure to a central system.  It also provides a convenient way to provide information about migrating existing users.
Why
---
Currently there's a mish-mash of local users across various boxes provisioned by hand, this is sub-optimal.  These accounts are not managed in any way and changes to anything requires changes to be propagated to other hosts by hand.  This also means that we don't have a good way to grant temporary access to machines nor do we have a good way to apply login policy across the fleet.
How
---
Shameless plug, I built tooling that does this.  Without getting into a huge discussion of why I went the long way round, the primary reason was it needed to be easy to run and easy to maintain.  It …
=> Migrate all accounts to central sources

ansible/roles/buildmaster/templates/master.cfg.j2, ansible/roles/buildmaster/templates/run.j2
1. make runit supervise buildmaster correctly.
2. the channel was so quiet when the xbps-builder was gone and we don't really need success notifications, failures are all that matters.
=> buildmaster changes

terraform/github/github_members.tf
Today we received the incredibly sad news that long time contributor
and maintainer Jürgen Buchmüller (pullmoll) has passed away.
As a standard measure of security, the access to any repositories is
being revoked from the account, but pullmoll will remain in the Void
Organization.
=> terraform/github: Remove push access from pullmoll

terraform/github/github_members.tf
@paper42 please confirm here that you accept this offer of a position on our maintainer team, at which time Duncaen will confirm that this PR is correct.
```
Terraform used the selected providers to generate the following execution plan. Resource actions are indicated with
the following symbols:
+ create
Terraform will perform the following actions:
+ resource "github_team_membership" "team_membership" {
+ etag     = (known after apply)
+ id       = (known after apply)
+ role     = "member"
+ team_id  = "2795568"
+ username = "paper42"
}
Plan: 1 to add, 0 to change, 0 to destroy.
```
=> terraform/github: Add paper42 to pkg-committers

services/pkg/xmandump/update
tested by replacing `xmandump` with `echo`
```
Dumping x86_64
-compress -c cache.json /mirror/current//x86_64-repodata /mirror/current//nonfree/x86_64-repodata
Dumping x86_64-musl
-compress -c cache.json /mirror/current/musl/x86_64-musl-repodata /mirror/current/musl/nonfree/x86_64-musl-repodata
Dumping armv7l
-compress -c cache.json /mirror/current//armv7l-repodata /mirror/current//nonfree/armv7l-repodata
Dumping armv7l-musl
-compress -c cache.json /mirror/current/musl/armv7l-musl-repodata /mirror/current/musl/nonfree/armv7l-musl-repodata
```
closes #87
=> services/pkg/xmandump/update: dump nonfree packages

terraform/github/github.tf
Opting this in since we're about to cut a release, and people can likely earn some PRs while we stabilize things and cut the release.
=> terraform/github: Opt in -mklive to hacktoberfest

ansible/group_vars/prod.yml, ansible/host_vars/a-fra-de.m.voidlinux.org.yml, ansible/inventory, terraform/do/dns.tf
Host `a-fra-de` is a new host in central Germany being sponsored by [23M](https://23m.com).  Provisioned as a tier 1 mirror with https://repo-de.voidlinux.org pointing at it.
=> New Host: a-fra-de

terraform/github/github.tf
closes void-linux/void-packages#43081
Unfortunately, enabling [organization discussions](https://docs.github.com/en/discussions/quickstart#enabling-github-discussions-on-your-organization) (which would put a link to void-packages' discussions on the org page) does not seem be exposed via the API at all currently, so if we want to enable that it will have to be done out-of-band for now.
There will also be some initial setup required for things like categories
=> terraform/github: enable discussions on void-packages

.github/workflows/build-all.yml, .github/workflows/build-pkg.yml, .github/workflows/infradocs.yml, .github/workflows/pkg-alps.yml, .github/workflows/pkg-lego.yml, .github/workflows/pkg-man-cgi.yml, .github/workflows/pkg-nginx.yml, .github/workflows/pkg-rspamd.yml, .github/workflows/pkg-rsync.yml, .github/workflows/pkg-sftpgo.yml, .github/workflows/pkg-xmandump.yml, docs/Dockerfile, services/pkg/alps/Dockerfile, services/pkg/debuginfod/Dockerfile, services/pkg/docker-bake.hcl, services/pkg/lego/Dockerfile, services/pkg/nginx/Dockerfile, services/pkg/rspamd/Dockerfile, services/pkg/rsync/Dockerfile, services/pkg/sftpgo/Dockerfile, services/pkg/xmandump/Dockerfile
this should make it easier to ensure that all infra packages are built the same. also takes advantage of the docker metadata action and updates the other actions used.
https://docs.github.com/en/actions/using-workflows/reusing-workflows
[example here](https://github.com/classabbyamp/void-infrastructure/actions/runs/5707269599)
=> update containers to new void images, clean up service container CI

services/nomad/build/build-rsyncd.nomad, services/nomad/mirror/shadow-rsyncd.nomad, services/nomad/mirror/sync.nomad
- services/nomad/build/build-rsyncd: don't serve shadow from this rsyncd
- services/nomad/mirror/shadow-rsyncd: split from build-rsyncd
- services/nomad/mirror/sync: use dynamic service lookup for shadow
=> shadow rsyncd

services/nomad/build/xbps-clean-sigs
the path to look for stale signatures in was changed
=> services/nomad/build/xbps-clean-sigs: fix signature cleanup

ansible/roles/buildmaster/defaults/main.yml
=> ansible/roles/buildmaster/defaults/main.yml: make subarch explicit

.github/workflows/pkg-popcorn.yml, services/pkg/docker-bake.hcl, services/pkg/popcorn/Dockerfile
=> services/pkg/popcorn: create popcorn container

ansible/host_vars/d-hel-fi.m.voidlinux.org.yml, services/nomad/apps/popcorn-report.nomad, services/nomad/apps/popcorn.nomad, terraform/hashistack/policy_popcorn.tf
this leaves only buildbot outside of nomad, I think.
should be deployed/merged in parts:
1. ~~merge and build container (and update the tag in nomad)~~
2. apply addition of popcorn host volume in ansible
3. copy all popcorn data from the current location to the volume
4. decommission ansible-based popcorn
5. run the nomad jobs
testing:
- ran all components in concert in docker (manually), which worked perfectly
- ran `nomad job plan` for each job (failed to place because the host volume doesn't exist yet, but no other errors)
fixes #76
=> popcorn: migrate to nomad

terraform/do/dns.tf
Revert "terraform/do/dns: popcorn is served by omniproxy"
This reverts commit 57d2007e998af39eef12696d179920559471edb6.
=> terraform/do/dns: rehome popcorn to d-hel-fi

services/nomad/build/build-rsyncd.nomad, services/nomad/build/buildsync.nomad, services/nomad/mirror/sync.nomad
- **services/nomad/build/build-rsyncd: ignore x86_64 packages in /aarch64/**
- **services/nomad/build/build-rsyncd: increase memory limit**
- **services/nomad/build/buildsync: --delay-updates**
- **services/nomad/mirror/sync: --delay-updates**
a few changes that should hopefully improve things
=> various rsync improvements

services/nomad/build/build-rsyncd.nomad, services/nomad/mirror/shadow-rsyncd.nomad
is OOMing, seems to be causing the missing repodata issue
=> services/nomad/mirror/shadow-rsyncd: increase memory limit

.editorconfig
enforces some basic style guidelines tree-wide and in yaml/hcl files
mostly adding this because i'm annoyed at my editor trying to do 4-space indents in hcl files
open to changing this/adding more filetypes
=> add basic editorconfig file

services/nomad/build/build-rsyncd.nomad, services/nomad/mirror/shadow-rsyncd.nomad
not sure why this started happening recently.
these are hardlinks and get dereferenced, leading to duplicate data on the mirrors and wasted space. this may have been causing some of the issues with repodatas going missing.
**this changeset has been deployed**
=> don't sync by_sha256 sources

services/nomad/build/buildsync.nomad, services/nomad/mirror/sync.nomad
b-hel-fi is already out of the DNS rotation for other reasons.
There has been a persistent issue where b-hel-fi has been filling up with files like:
```
/data/dist_sources/chromium-131.0.6778.69/.chromium-131.0.6778.69.tar.xz.c1MIVQ
/data/dist_sources/chromium-131.0.6778.69/.chromium-131.0.6778.69.tar.xz.OMWNDr
/data/dist_sources/chromium-131.0.6778.69/.chromium-131.0.6778.69.tar.xz.DE9ngv
/data/dist_sources/chromium-131.0.6778.69/.chromium-131.0.6778.69.tar.xz.T2lCDe
/data/dist_sources/chromium-131.0.6778.69/.chromium-131.0.6778.69.tar.xz.HJvalz
/data/dist_sources/chromium-131.0.6778.69/.chromium-131.0.6778.69.tar.xz.gWuXSr
/data/dist_sources/chromium-131.0.6778.69/.chromium-131.0.6778.69.tar.xz.a55q6u
/data/dist_sources/chromium-131.0.6778.69/.chromium-131.0.6778.69.tar.xz.9W7FHE …
```
=> disable sync to b-hel-fi, add filters to buildsync

services/pkg/sftpgo/Dockerfile
will require migration as discussed before full deployment, but the container can be updated
adding rsync will allow sftpgo to "talk" rsync: https://docs.sftpgo.com/latest/ssh/#ssh-commands
=> services/pkg/sftpgo: update, add rsync, move env to nomad

ansible/host_vars/b-lej-de.m.voidlinux.org.yml
Adjust the default IPv6 route based on changes at Hetzner.
=> ansible/host_vars/b-lej-de: Set IPv6 default route.

.github/workflows/build-pkg.yml
v3 doesn't work with our version of buildx
=> .github/workflows/build-pkg: update docker/bake-action

services/nomad/build/buildbot-worker.nomad, services/nomad/build/buildbot.cfg, services/nomad/build/buildbot.nomad
- **services/pkg/buildbot{,-builder}: update to buildbot 4.1.0**
- **services/nomad/buildbot: update config to split logs per-package**
=> buildbot 4.2 updates

services/nomad/build/buildbot.cfg, services/nomad/build/buildbot.nomad, services/pkg/buildbot-builder/Dockerfile
this should fix ordering issues with split logs
not yet applied, waiting for builds to finish
=> services/nomad/build/buildbot: sort packages before printing

ansible/host_vars/j-hel-fi.m.voidlinux.org.yml, services/nomad/monitoring/vector.nomad, services/nomad/monitoring/vmlogs.nomad
Loki is a royal pain to run and breaks in weird ways when we have to restart it.  I've been running victoria logs in some other networks now and quite like it.  This is running in dual-write mode so both loki and vmlogs are receiving data concurrently.
=> Migrate to VictoriaLogs

services/nomad/build/buildbot-worker.nomad
this also decouples the makejobs from the amount of cpu used to schedule with nomad
alternatively, we could keep using the `cores` reservation, but make it separate from makejobs
**APPLIED**
=> services/nomad/build/buildbot-worker: use cpu instead of cores for scheduling

services/nomad/apps/devspace.nomad, services/nomad/apps/popcorn.nomad, services/nomad/infrastructure/nginx-control.nomad, services/nomad/infrastructure/nginx-mirror.nomad, services/pkg/man-cgi/Dockerfile
deployed:
- services/nomad/apps/popcorn: update nginx
- services/nomad/apps/devspace: update nginx
- services/nomad/infrastructure/nginx-mirror: update nginx
- services/nomad/infrastructure/nginx-control: update nginx
not deployed:
- services/pkg/man-cgi: update nginx
=> update nginx in services

ansible/group_vars/prod.yml, ansible/host_vars/a-sea-us.m.voidlinux.org.yml, ansible/inventory, ansible/network.yml, ansible/roles/void-mesh/templates/void0.conf.j2, terraform/do/dns.tf
`a-sea-us` is our first native arm64 compute host.
=> Add new host: a-sea-us
